name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check code formatting with Prettier
      run: |
        npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,md}" || {
          echo "Code formatting issues found. Run 'npx prettier --write .' to fix."
          exit 1
        }
      continue-on-error: true
      
    - name: Check for TODO/FIXME comments
      run: |
        if grep -r "TODO\|FIXME" src/ --exclude-dir=node_modules; then
          echo "Found TODO/FIXME comments. Please address them before merging."
        fi
      continue-on-error: true
      
    - name: Bundle size analysis
      run: |
        npm run build
        npx next-bundle-analyzer || true
      continue-on-error: true
      
    - name: Check dependencies for updates
      run: |
        npx npm-check-updates --doctor || true
      continue-on-error: true